---
- name: Manage MySQL Docker Compose setup
  hosts: prodVm
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Ensure you're using Python 3
    compose_dir: ~/mysql_docker_setup  
    compose_file_path: "{{ compose_dir }}/docker-compose.yml"  
    db_name: timesheet-devops-db
    db_user: seif
    db_password: ""  
    root_password: ""  

  tasks:
    - name: Install pip3 if not present (Ubuntu/Debian)
      apt:
        name: python3-pip
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install pip3 if not present (RHEL/CentOS)
      yum:
        name: python3-pip
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    # - name: Install Docker Compose Python library
    #   pip:
    #     name: docker-compose
    #     state: present
    #   become: yes

    # - name: Ensure Docker SDK for Python is installed
    #   pip:
    #     name: docker
    #     state: latest
    #   become: yes

    - name: Create Docker Compose directory
      file:
        path: "{{ compose_dir }}"
        state: directory
        mode: '0755'
    
    - name: Ensure the Docker network "timesheet-network" exists
      docker_network:
        name: timesheet-network
        state: present

    - name: Create Docker Compose file
      copy:
        dest: "{{ compose_file_path }}"
        content: |
          services:
            mysql:
              image: mysql
              container_name: mysql
              environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                MYSQL_ROOT_PASSWORD: {{ root_password }}
                MYSQL_DATABASE: {{ db_name }}
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
              ports:
                - "3306:3306"
              volumes:
                - mysql_data:/var/lib/mysql
          volumes:
            mysql_data:
          networks:
            mysql-network:
              external: true

    - name: Check if MySQL container is already running
      command: docker compose ps -q
      args:
        chdir: "{{ compose_dir }}"
      register: compose_status
      changed_when: false

    - name: Ensure Docker Compose is up
      command: docker compose up -d
      args:
        chdir: "{{ compose_dir }}"
      when: compose_status.stdout == ""

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        timeout: 60 # Use the increased wait time
        state: started

    # - name: Create a table if it doesn't exist
    #   mysql_query:
    #     login_user: "{{ db_user }}"
    #     login_password: "{{ db_password }}"
    #     db: "{{ db_name }}"
    #     query: "CREATE TABLE IF NOT EXISTS my_table (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255));"
    #   register: query_result

    # - name: Output the table creation status
    #   debug:
    #     msg: "Table created or already exists."
    #   when: query_result.changed == false
