global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#-----------promethus-----------------------------
- job_name: 'prometheus'
  static_configs:
  - targets: ['192.168.43.10:9090']


